default_language_version:
  python: python3

exclude: ^(venv|\.venv|build|dist|__pycache__|\.git)/

repos:
  - repo: local
    hooks:
      # -------------------- BLACK --------------------
      - id: black
        name: black (uv)
        entry: uv run --no-sync black
        language: system
        types: [python]
        args: ["--line-length=88"]

      # -------------------- ISORT --------------------
      - id: isort
        name: isort (uv)
        entry: uv run --no-sync isort
        language: system
        types: [python]
        args: ["--profile=black", "--line-length=88"]

      # -------------------- AUTOFLaKE --------------------
      - id: autoflake
        name: autoflake (uv)
        entry: uv run --no-sync autoflake
        language: system
        types: [python]
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --in-place

      # -------------------- FLAKE8 --------------------
      - id: flake8
        name: flake8 (uv)
        entry: uv run --no-sync flake8
        language: system
        types: [python]
        args: ["--max-line-length=88"]

      # -------------------- PYLINT --------------------
      - id: pylint
        name: pylint (uv)
        entry: uv run --no-sync pylint
        language: system
        types: [python]
        args:
          - --output-format=colorized
